name: Caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: 'use cache'
                default: true
                type: boolean
            node-version:
                description: 'Node.js version'
                default: '20.x'
                type: choice
                options:
                    - '18.x'
                    - '20.x'
                    - '21.x'
jobs:
    install-deps:
       runs-on: ubuntu-latest
       defaults:
        run:
            working-directory: caching/react-app
       outputs:
        deps-cache-key: ${{ steps.calculate-cache-key.outputs.CACHE_KEY }}
       steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ inputs.node-version }}
        
        - name: Calculate cache key
          id: calculate-cache-key
          run:  echo "CACHE_KEY=deps-node-modules-${{ hashFiles('caching/react-app/package-lock.json') }} >> $GITHUB_OUTPUT"

        - name: Download cached dependencies
          uses: actions/cache@v3
          if: ${{ inputs.use-cache }}
          id: cache-deps
          with:
            path: caching/react-app/node_modules
            key: ${{ steps.calculate-cache-key.outputs.CACHE_KEY }}
        
        - name: Install dependencies
          if: steps.cache-deps.outputs.cache-hit != 'true'
          run: npm install 
    
    lint-test:
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
          run:
            working-directory: caching/react-app
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ inputs.node-version }}
            
            - name: Download cached dependencies
              uses: actions/cache@v3
              if: ${{ inputs.use-cache }}
              id: cache-deps
              with:
                path: caching/react-app/node_modules
                key: ${{ needs.install-deps.outputs.deps-cache-key }}

            - name: Testing
              run: npm run test
            
            - name: Linting
              run: echo "Linting"

    build:
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
          run:
            working-directory: caching/react-app
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ inputs.node-version }}
            
            - name: Download cached dependencies
              uses: actions/cache@v3
              if: ${{ inputs.use-cache }}
              id: cache-deps
              with:
                path: caching/react-app/node_modules
                key: ${{ needs.install-deps.outputs.deps-cache-key }}
            
            - name: Building
              run: npm run build