name: Caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: 'use cache'
                default: true
                type: boolean
            node-version:
                description: 'Node.js version'
                default: '20.x'
                type: choice
                options:
                    - '18.x'
                    - '20.x'
                    - '21.x'
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: caching/react-app
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ inputs.node-version }}
            
            - name: Download cached dependencies
              uses: actions/cache@v3
              if: ${{ inputs.use-cache }}
              id: cache-deps
              with:
                path: caching/react-app/node_modules
                key: deps-node-modules-${{ hashFiles('caching/react-app/package-lock.json') }}
            
            - name: Install dependencies
              if: steps.cache-deps.outputs.cache-hit != 'true'
              run: npm install
            
            - name: Testing caching
              run: npm run build
            
            - name: Deploying to non prod
              run: echo "Deploying to non prod environment"