name: Custom actions composite

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: custom-actions/react-app 
        steps:
            - uses: actions/checkout@v4
            - name: Setup node and NPM dependencies
              uses: ./.github/actions/composite-cache-deps
              with:
                node-version: 20.x
                working-directory: custom-actions/react-app
            - name: Test
              run: npm Test
            - name: build
              run: npm run build