name: Using actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ".github/workflows/"
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Print repo files
              run: ls -la